name: quran_shazam
description: Quran verse recognition app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  record: ^5.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
